In [38]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50], dtype = int)

In [35]:
print(arr[2])

30


In [4]:
arr[3] = 100

In [5]:
print(arr)

[ 10  20  30 100  50]


In [7]:
print(arr[len(arr)-1])

50


In [10]:
for i in range(1, len(arr), 2):
    print(arr[i])

20
100


In [25]:
new_array = np.zeros(10)

In [26]:
print(new_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [39]:
def leftShift(arr):
    temp = arr[0]
    for i in range(len(arr)-1):
        arr[i] = arr[i+1]
        print("for i = ", i, "array = ", arr)
    arr[len(arr)-1] = temp
    return arr

In [40]:
print(arr)
leftShift(arr)

[10 20 30 40 50]
for i =  0 array =  [20 20 30 40 50]
for i =  1 array =  [20 30 30 40 50]
for i =  2 array =  [20 30 40 40 50]
for i =  3 array =  [20 30 40 50 50]


array([20, 30, 40, 50, 10])